# === PromptTick 基础配置（Round 1） ===

# 扫描节奏（下一轮才用到，这里先占位）
interval_seconds: 300           # 每轮间隔秒数，示例值：5分钟
batch_size: 1                   # 每轮处理文件个数上限（占位）

# 文件过滤与排序
file_extensions: [".txt", ".md"]  # 仅处理这些后缀（占位）
ordering: "name"                 # name|mtime（占位）

# 目录
input_dir: "in_prompts"
output_dir: "out"
log_dir: "logs"
state_path: "state.json"

# 适配器选择
adapter: "echo_adapter"          # 可切换为 generic_http_adapter

# 日志级别（INFO/DEBUG）
log_level: "INFO"

# 预留的外部 API 区域（后续轮次使用）
openai:
  model: "gpt-4.1-mini"
  temperature: 0.7
  max_output_tokens: 800

generic_http:
  url: ""              # e.g. https://api.example.com/generate
  method: "POST"
  timeout: 60
  headers: {}          # 支持 ${ENV:KEY} 占位；示例：Authorization: "Bearer ${ENV:API_TOKEN}"
  body_template: ""    # 示例：{"prompt": "${PROMPT}"}
  response_json_pointer: ""  # 示例：/data/text
  retries:
    max_attempts: 3
    backoff_seconds: 1.0
    retry_on_status: [429, 500, 502, 503, 504]
